### ISSUE TITLE
Add more reviewers

### ISSUE THREAD

**Issue by sameo** [riscv-non-isa/riscv-ap-tee-io#19]
@rpsene Could we please add more people to the reviewers list for this repo? For example I can not Ravi or Ved to the reviewers, could we please add them?

**Comment by rpsene** [comment]
@sameo let me check.

**Comment by rpsene** [comment]
@sameo I added Ved and Ravi and gave you admin rights so you can invite anyone required to help.

**Comment by sameo** [comment]
Thanks a lot @rpsene
