### ISSUE TITLE
`HROT` needs to be defined in the Glossary

### ISSUE THREAD

**Issue by steven-bellock** [riscv-non-isa/riscv-ap-tee-io#51]
The glossary defines `Root of Trust / ROT` as
>Isolated HW/SW subsystem with an immutable ROM firmware and isolated compute and memory elements that form the Trusted Compute Base of a TEE system.

Later on the specification uses `hardware Root-of-Trust (HROT)`. Presumably this is a sub-system that is entirely hardware and does not contain any mutable code, and the glossary should distinguish between the two.

**Comment by sameo** [comment]
I think it would make sense to only use ROT and remove the HROT occurrence.
