### ISSUE TITLE
[Qualcomm feedback] 3.2.2. Platform Hardware Components - CoVE-IO Manifest

### ISSUE THREAD

**Issue by jyao1** [riscv-non-isa/riscv-ap-tee-io#74]
Reference: https://lists.riscv.org/g/tech-ap-tee-io/topic/103498833#47

Again, what is the rationale of burdening HROT with all this complexity?

**Comment by sameo** [comment]
The idea behind that requirement is to keep the TSM implementation generic and not specific to any platform.

Unlike devices, RP IDE key management is not specified and each RISC-V platform may have its own protocol or interface for that. Having TSM directly support that means we would eventually have to support a growing list of vendor and hardware specific interfaces. On the other hand, RoTs are very much bound to the platform they running on and it seems reasonable to expect them to be able to program RP IDE keys using a platform specific interface. Moreover they are part of the TCB and can securely hold the IDE keys.

So if we want to keep the TSM implementation platform agnostic, have it generate and own the RP IDE keys but delegate the IDE key programming to the RoT, we need to find a way for the TSM to share those keys with the RoT. The PCIe IDE KM protocol is basically designed for that, and  relies on SPDM and DOE for doing so.

So I don't think we're burdening the RoT with complexity, but rather preserving the TSM from carrying platform and vendor specific implementations.

**Comment by sameo** [comment]
Fixed with https://github.com/riscv-non-isa/riscv-ap-tee-io/pull/105 as well.
