### ISSUE TITLE
[Qualcomm feedback] 7.1.2. PCIe Root Port Registration 

### ISSUE THREAD

**Issue by jyao1** [riscv-non-isa/riscv-ap-tee-io#83]
Reference: https://lists.riscv.org/g/tech-ap-tee-io/topic/103498833#47

This model  does not seem to work when there are distrusting supervisor domains. why does the TSM have to generate and own the keys?

**Comment by jyao1** [comment]
@sameo , do we support multiple TSMs ?

**Comment by sameo** [comment]
> It is understood that TSM needs to own, but which one in the case of multiple supervisor domains (hence multiple distrusting TSMs). Maybe the wording might be changed as "the corresponding/respective TSM owns the SPDM session...". 

Yes, that's the intention. The TSM owns the keys for any device that the host domain requests it to connect to.
I'll clarify that.
