### ISSUE TITLE
[Qualcomm feedback] 7.3.2. IDE Link - ECAP

### ISSUE THREAD

**Issue by jyao1** [riscv-non-isa/riscv-ap-tee-io#86]
Reference: https://lists.riscv.org/g/tech-ap-tee-io/topic/103498833#47

> 3. Programing the PCIe switch between the device and PCIe root port, such as IDE Control Register -
Flow-Through IDE Stream Enabled

According to pcie spec the control of this extended capability by the untrusted host is an issue, it needs to be policed by the concerned TSMs  (11.5.8)

**Comment by jyao1** [comment]
Not sure why it is an issue.

VMM can program it.
VMM sends LOCK_INTERFACE_REQUEST. If VMM does something wrong, DSM will reject.
VMM assigns TDI to TVM. TVM sends GET_INTERFACE_REPORT. If VMM does something wrong, TVM will reject.

**Comment by ozkoyuncu** [comment]
In a normal (good citizen case) I agree, however for the IDE extended capability register, wondering whether giving direct access to VMM enables a TOCTOU type of attack. for this reason pcie spec explicitly requires that either the access is policed by the TSM or any change is detected (how is not clear). otherwise free access to this register may compromise the IDE flow of a TDI. ie once configured and reported, how does tsm ensure integrity of this register. pls see section 11.5.8. Otherwise a note in your spec along those lines might clarify...

**Comment by jyao1** [comment]
There are couples of things:

For PCIe switch:
1) A switch is NOT TCB in TEE-IO use case. TEE-IO uses selective IDE, but NOT link IDE. A switch can be a malicious one. The only requirement here is to allow switch to passthru the selective IDE stream.
2) A VMM can program the switch register at any time, including disable the switch IDE control register. It is a typical Denial-of-Service (DOS) attack. However, DOS attack is out of scope in confidential computing.
Since Switch is NOT TCB and DOS attack is out of scope, I am not sure where is the issue.

For PCIe Root Port:
1) PCIe Root Port should be designed to support TEE-IO. It is implementation specific. 
2) The PCIe Root Port implementation shall NOT allow any untrusted party (VMM) to change the secure configuration. TSM should be the only entity to touch the secure configuration.
The Root Port programming is already covered in "The TSM is responsible for" section.

For PCIe Device:
1) Device should follow PCIe standard TDISP chapter.
2) DSM should control the setting.

Not sure which TOCTOU attack you are referring to. Please enlighten me on that.

**Comment by ozkoyuncu** [comment]
Understood. I think the "TSM is responsible for" section clarifies the  RP  concern; 
so for the device, it is under the control of DSM right? the statement in the spec that said  
"The host supervisor domain manager is responsible for:  Setting the device PCIe device IDE PCI Extended Capability." 
was not very clear to us. sounds like temporally allowed by DSM and later unauthorized (vmm) access is revoked by DSM after SPDM session is established?

**Comment by jyao1** [comment]
> "The host supervisor domain manager is responsible for: Setting the device PCIe device IDE PCI Extended Capability."
was not very clear to us. sounds like temporally allowed by DSM and later unauthorized (vmm) access is revoked by DSM after SPDM session is established?

Of course the VMM, as a trusted component, can do that to DOS the system.
Then the DSM takes the responsibility to move TDI to ERROR state immediately. 
Please refer to - PCIe 6.1. 11.2.6 DSM Tracking and Handling of Locked TDI Configurations (Informative) (page 1581)

**Comment by sameo** [comment]
@ozkoyuncu I think this issue can be closed. Is that ok with you @ozkoyuncu ?

**Comment by ozkoyuncu** [comment]
> @ozkoyuncu I think this issue can be closed. Is that ok with you @ozkoyuncu ?

Yes this issue can be closed. thx
