### ISSUE TITLE
[Qualcomm feedback] 7.7. Device and Interface Lifecycle

### ISSUE THREAD

**Issue by jyao1** [riscv-non-isa/riscv-ap-tee-io#89]
Reference: https://lists.riscv.org/g/tech-ap-tee-io/topic/103498833#47

> At any point in time, it can reclaim that physical resource by
unbinding (step 8a) it from its TVM.

Is it possible for the host to "yank" the physical resource without interacting with the TSM?

**Comment by jyao1** [comment]
If VMM does not talk to TSM, TSM will think the resource is still assigned and locked.

VMM cannot re-assign the resource to other TVM.

**Comment by sameo** [comment]
So it is possible for the host to yank the physical resource without letting the TSM know. As long as this resource is a TEE-IO compliant device, the TSM won't be able to reassign or re-use it without bringing it back to the UNLOCKED TDISP state, i.e without having the device DSM flushing any pending confidential data.

So the host can DoS the TDI from the TVM, and that's fine. But it wouldn't be able to directly get any confidential data or have another TVM get that data, for TEE-IO/TDISP compliant devices.

@jyao1 Do you think we should expand on that in the spec?

**Comment by jyao1** [comment]
I think we must describe the valid usage. And we can conditionally describe some invalid usages, for clarification purpose.

But we are not able to list all invalid cases, because that will be too much.

**Comment by sameo** [comment]
> I think we must describe the valid usage. And we can conditionally describe some invalid usages, for clarification purpose.

And by valid usage here we mean a "happy path", where the VMM would gracefully ask the TSM to disconnect from the device. And invalid usage would be a high level description of an implicit removal.

> But we are not able to list all invalid cases, because that will be too much.

Agreed.

**Comment by rsahita** [comment]
behavior expected on surprise removal of the TDI bound to a TVM should be described IMO (as informative) - also i think it is mentioned in the threat model?
